version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    labels:
      - dependabot
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    reviewers:
      - "MeritAmerica/eng-product"
